### ISSUE TITLE
K8s HA Deployment

### ISSUE THREAD

**Issue by coolpalani** [yoshz/ansible-role-kubernetes#1]
Could you add Kubernetes with HA deployment using Ansible.

**Comment by yoshz** [comment]
This role can already be used in HA mode as it allows you to deploy multiple master nodes.

**Comment by coolpalani** [comment]
I am facing issue in certificates.
I created the directory path but it's still failing playbook.

TASK [yoshz.kubernetes : Install CA certificate] ********************************************************************************************************************
task path: /etc/ansible/roles/yoshz.kubernetes/tasks/certs-install.yml:10
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /etc/ansible/certs/ca.crt
failed: [node4] (item=ca.crt) => {"changed": false, "item": "ca.crt", "msg": "Could not find or access 'certs/ca.crt'\nSearched in:\n\t/etc/ansible/roles/yoshz.kubernetes/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/certs/ca.crt\n\t/etc/ansible/files/certs/ca.crt\n\t/etc/ansible/certs/ca.crt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /etc/ansible/certs/ca.crt
failed: [node5] (item=ca.crt) => {"changed": false, "item": "ca.crt", "msg": "Could not find or access 'certs/ca.crt'\nSearched in:\n\t/etc/ansible/roles/yoshz.kubernetes/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/certs/ca.crt\n\t/etc/ansible/files/certs/ca.crt\n\t/etc/ansible/certs/ca.crt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /etc/ansible/certs/ca.crt
failed: [node1] (item=ca.crt) => {"changed": false, "item": "ca.crt", "msg": "Could not find or access 'certs/ca.crt'\nSearched in:\n\t/etc/ansible/roles/yoshz.kubernetes/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/certs/ca.crt\n\t/etc/ansible/files/certs/ca.crt\n\t/etc/ansible/certs/ca.crt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /etc/ansible/certs/ca.crt
failed: [node2] (item=ca.crt) => {"changed": false, "item": "ca.crt", "msg": "Could not find or access 'certs/ca.crt'\nSearched in:\n\t/etc/ansible/roles/yoshz.kubernetes/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/certs/ca.crt\n\t/etc/ansible/files/certs/ca.crt\n\t/etc/ansible/certs/ca.crt"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /etc/ansible/certs/ca.crt
failed: [node3] (item=ca.crt) => {"changed": false, "item": "ca.crt", "msg": "Could not find or access 'certs/ca.crt'\nSearched in:\n\t/etc/ansible/roles/yoshz.kubernetes/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/files/certs/ca.crt\n\t/etc/ansible/roles/yoshz.kubernetes/tasks/certs/ca.crt\n\t/etc/ansible/files/certs/ca.crt\n\t/etc/ansible/certs/ca.crt"}

**Comment by yoshz** [comment]
Did you set the `k8s_certs_src` variable? Path should be relative from the playbook directory.

**Comment by coolpalani** [comment]
I had setup that k8s_certs_src in ansible variable file itself.


*Best Regards,*
*Palanisamy*
